name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
          - 20.x

    services:
      elasticmq:
        image: softwaremill/elasticmq
        options: -p 9324:9324 --name elasticmq

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ElasticMQ Configuration
        run: |
          cp ${{ github.workspace }}/.github/build/elasticmq.conf /tmp/elasticmq.conf
          docker cp /tmp/elasticmq.conf elasticmq:/opt/elasticmq.conf
          docker restart elasticmq

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Check lint
        run: pnpm run lint

      - name: Run Tests
        run: pnpm run test:e2e
